# Generated by Django 5.2.8 on 2025-11-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagebanner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif ?'),
        ),
    ]
