# Generated by Django 5.2.8 on 2025-11-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_pagebanner_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='Our Services', max_length=100, verbose_name='Titre Principal')),
                ('sub_title', models.CharField(default='what we do', max_length=100, verbose_name='Sous-titre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image de fond')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif ?')),
            ],
            options={
                'verbose_name': 'Bannière Services',
                'verbose_name_plural': 'Bannière Services',
            },
        ),
    ]
