# Generated by Django 5.2.8 on 2025-11-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_servicesbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetailBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='transportation', max_length=50, verbose_name='Catégorie (ex: transportation)')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'article")),
                ('author', models.CharField(default='John', max_length=50, verbose_name="Nom de l'auteur")),
                ('publish_date', models.DateField(verbose_name='Date de publication')),
                ('comments_count', models.CharField(default='3', max_length=10, verbose_name='Nombre de commentaires')),
                ('views_count', models.CharField(default='5.5K', max_length=10, verbose_name='Nombre de vues')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_details/', verbose_name='Image de fond')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif ?')),
            ],
            options={
                'verbose_name': 'Bannière Détail Blog',
                'verbose_name_plural': 'Bannière Détail Blog',
            },
        ),
    ]
