# Generated by Django 5.2.8 on 2025-11-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_blogdetailbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du client/prix (pour info)')),
                ('image', models.ImageField(upload_to='awards/', verbose_name='Logo')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Logo Récompense',
                'verbose_name_plural': 'Logos Récompenses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AwardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='International awards 2024', max_length=100, verbose_name='Titre Principal')),
                ('subtitle', models.CharField(default='Awards', max_length=100, verbose_name='Sous-titre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Afficher la section ?')),
            ],
            options={
                'verbose_name': 'Section Récompenses (Titres)',
                'verbose_name_plural': 'Section Récompenses (Titres)',
            },
        ),
        migrations.CreateModel(
            name='BlogPostHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Air Freight', max_length=100, verbose_name='Catégorie')),
                ('title', models.CharField(max_length=255, verbose_name="Titre de l'article")),
                ('author_name', models.CharField(default='John', max_length=50, verbose_name='Auteur')),
                ('publish_date', models.DateField(verbose_name='Date de publication')),
                ('comments_count', models.IntegerField(default=3, verbose_name='Nb Commentaires')),
                ('views_count', models.CharField(default='5.5K', max_length=20, verbose_name='Nb Vues (ex: 5.5K)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_headers/', verbose_name='Image de fond')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif ?')),
            ],
            options={
                'verbose_name': 'En-tête Article Blog',
                'verbose_name_plural': 'En-têtes Article Blog',
            },
        ),
    ]
