# Generated by Django 5.2.8 on 2025-11-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_awardlogo_awardsection_blogpostheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='Talk or Meet with Us', max_length=100, verbose_name='Titre Principal (Gauche)')),
                ('sub_title', models.CharField(default='Get In Touch', max_length=100, verbose_name='Sous-titre (Gauche)')),
                ('address_title', models.CharField(default='Get Us Here', max_length=50, verbose_name='Titre Adresse')),
                ('address', models.TextField(default='1355 Market St, Suite 900\nSan Francisco, CA 94', verbose_name='Adresse')),
                ('phone_title', models.CharField(default='Call Us', max_length=50, verbose_name='Titre Téléphone')),
                ('phone', models.CharField(default='+1 123 456 7890', max_length=50, verbose_name='Numéro de téléphone')),
                ('email_title', models.CharField(default='Write Us', max_length=50, verbose_name='Titre Email')),
                ('email', models.EmailField(default='info@thisone.com', max_length=254, verbose_name='Email de contact')),
                ('form_main_title', models.CharField(default='Let Us Know Here', max_length=100, verbose_name='Titre Formulaire')),
                ('form_sub_title', models.CharField(default='Estimate Project', max_length=100, verbose_name='Sous-titre Formulaire')),
            ],
            options={
                'verbose_name': 'Section Contact (Infos)',
                'verbose_name_plural': 'Section Contact (Infos)',
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message Reçu', 'verbose_name_plural': 'Messages Reçus'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='comment',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Web'),
        ),
    ]
