# Generated by Django 5.2.8 on 2025-11-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_contactsection_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='features/')),
                ('accordion_title_1', models.CharField(max_length=255)),
                ('accordion_text_1', models.TextField()),
                ('accordion_title_2', models.CharField(max_length=255)),
                ('accordion_text_2', models.TextField()),
                ('accordion_title_3', models.CharField(max_length=255)),
                ('accordion_text_3', models.TextField()),
            ],
        ),
    ]
