# Generated by Django 5.2.8 on 2025-11-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_featuresection'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('button_text', models.CharField(default='GET A QUOTE', max_length=50)),
                ('button_link', models.URLField(default='#')),
            ],
        ),
    ]
