# Generated by Django 5.2.7 on 2025-11-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_joinussection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='MapSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Notre Localisation', max_length=100, verbose_name='Titre (pour admin)')),
                ('map_url', models.TextField(help_text="Copiez uniquement le lien entre les guillemets de 'src' dans le code d'intégration Google.", verbose_name='Lien Google Maps (src)')),
                ('height', models.IntegerField(default=400, verbose_name='Hauteur (px)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Afficher la carte ?')),
            ],
            options={
                'verbose_name': 'Configuration de la Carte',
                'verbose_name_plural': 'Configuration de la Carte',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('roadandtruck', 'Road & Truck'), ('airplane', 'Airplane'), ('maritime', 'Maritime'), ('videos', 'Videos')], max_length=20)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('period', models.CharField(default='month', max_length=20)),
                ('features', models.TextField()),
                ('popular', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='team/')),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('dribbble', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='testimonials/')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='Why Choose us', max_length=100, verbose_name='Petit titre (Haut)')),
                ('title', models.CharField(default='We are logistic improving our skills...', max_length=200, verbose_name='Titre Principal')),
                ('description', models.TextField(verbose_name='Description')),
                ('call_title', models.CharField(default='BOOK THROUGH CALL', max_length=100, verbose_name='Titre appel')),
                ('phone_number', models.CharField(default='+1 234 567 8910', max_length=20, verbose_name='Numéro affiché')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Image de fond')),
                ('is_active', models.BooleanField(default=True, verbose_name='Afficher la section ?')),
            ],
            options={
                'verbose_name': 'Section Pourquoi Nous Choisir',
                'verbose_name_plural': 'Section Pourquoi Nous Choisir',
            },
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='created_at',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
