# Generated by Django 5.2.7 on 2025-11-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_client_mapsection_portfolioitem_pricingplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('category', models.CharField(choices=[('roadandtruck', 'Road & Truck'), ('airplane', 'Airplane'), ('maritime', 'Maritime'), ('videos', 'Videos')], max_length=50, verbose_name='Catégorie')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Image')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Lien Vidéo (Vimeo/Youtube)')),
            ],
        ),
    ]
