# Generated by Django 5.2.7 on 2025-12-03 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_portfolioproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloc_spl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='blog_images/', verbose_name='Image Principale')),
                ('content', models.TextField(verbose_name="Contenu de l'article")),
                ('category_name', models.CharField(default='Technologie', max_length=100, verbose_name='Nom de la catégorie')),
                ('tags_string', models.CharField(help_text='Séparez les tags par des virgules', max_length=200, verbose_name='Tags (texte)')),
                ('author_name', models.CharField(default='Admin', max_length=100, verbose_name="Nom de l'auteur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='bloc_spr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Titre de l'article")),
                ('slug', models.SlugField(help_text="L'URL de l'article (ex: mon-super-article)", unique=True)),
                ('image', models.ImageField(upload_to='blog_images/', verbose_name='Image Principale')),
                ('content', models.TextField(verbose_name="Contenu de l'article")),
                ('category_name', models.CharField(default='Général', max_length=100, verbose_name='Nom de la catégorie')),
                ('tags_string', models.CharField(help_text='Séparez les tags par des virgules (ex: Web, Design, SEO)', max_length=200, verbose_name='Liste des tags')),
                ('author_name', models.CharField(default='Admin', max_length=100, verbose_name="Nom de l'auteur")),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='author_images/', verbose_name="Photo de l'auteur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='service_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(default='/month', max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='popular',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='currency',
            field=models.CharField(default='$', max_length=5, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='description',
            field=models.CharField(default='All plans include a 30 day trial!', max_length=200),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Est-ce le plan populaire ?'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='Titre (ex: Basic)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='period',
            field=models.CharField(default='/month', max_length=20, verbose_name='Période'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price',
            field=models.IntegerField(verbose_name='Prix'),
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Texte de la fonctionnalité')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='website.pricingplan')),
            ],
        ),
        migrations.CreateModel(
            name='service2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='website.pricingplan')),
            ],
        ),
    ]
